# This override file should be used when running this service in isolation
# to provide required sibling services for local testing

services:
  ? Danny-Test
  : build:
      target: development
    ports:
      - "3007:3007"
    volumes:
      - ./src/Danny.Test.Api:/home/dotnet/src/Danny.Test.Api
      - ./src/Danny.Test.Core:/home/dotnet/src/Danny.Test.Core